# Generated by Django 3.1.2 on 2020-10-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("expense", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="month",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="expense",
            name="year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="expense",
            name="expense_id",
            field=models.CharField(
                default="4e3ad567-c223-49fe-9000-1262449b437c",
                max_length=120,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="expense", unique_together={("month", "year")}
        ),
    ]
