# Generated by Django 3.1.2 on 2020-10-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("expense", "0002_auto_20201023_0936")]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="dependent",
            field=models.FloatField(verbose_name="Dependent"),
        ),
        migrations.AlterField(
            model_name="expense",
            name="doctor",
            field=models.FloatField(verbose_name="Doctor"),
        ),
        migrations.AlterField(
            model_name="expense",
            name="expense_id",
            field=models.CharField(
                default="d2222807-98fb-46c9-9329-481030145156",
                max_length=120,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="family",
            field=models.FloatField(verbose_name="Family"),
        ),
        migrations.AlterField(
            model_name="expense",
            name="gym",
            field=models.FloatField(verbose_name="Gym"),
        ),
        migrations.AlterField(
            model_name="expense",
            name="misc",
            field=models.FloatField(verbose_name="Miscallenaous"),
        ),
        migrations.AlterField(
            model_name="expense",
            name="personal",
            field=models.FloatField(verbose_name="Personal"),
        ),
        migrations.AlterField(
            model_name="expense",
            name="physio",
            field=models.FloatField(verbose_name="Physio"),
        ),
        migrations.AlterField(
            model_name="expense",
            name="rent",
            field=models.FloatField(verbose_name="Rent"),
        ),
        migrations.AlterField(
            model_name="expense",
            name="saving",
            field=models.FloatField(verbose_name="Saving"),
        ),
    ]
