# Generated by Django 3.1.2 on 2020-10-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("expense", "0003_auto_20201024_1816")]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="expense_id",
            field=models.CharField(
                default="d3ccef36-3709-4d60-b5fe-d673ee9d3933",
                max_length=120,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="total",
            field=models.FloatField(blank=True, null=True, verbose_name="Total"),
        ),
    ]
