# Generated by Django 3.1.2 on 2020-10-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("expense", "0004_auto_20201024_1825")]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="expense_id",
            field=models.CharField(
                default="52fef773-d33c-4c7d-9389-703a9e1242f9",
                max_length=120,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="extra",
            field=models.FloatField(blank=True, null=True, verbose_name="Extra"),
        ),
    ]
