# Generated by Django 3.1.2 on 2020-11-08 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("invoice", "0002_auto_20201108_2005")]

    operations = [
        migrations.RemoveField(model_name="invoice", name="gross_amount"),
        migrations.RemoveField(model_name="invoice", name="tax"),
        migrations.CreateModel(
            name="BaseSalarySetUp",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("base_salary", models.FloatField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="invoice.company",
                    ),
                ),
                (
                    "tax",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="invoice.taxsetup",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="invoice",
            name="base_pay",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="invoice.basesalarysetup",
            ),
            preserve_default=False,
        ),
    ]
