# Generated by Django 3.1.2 on 2020-11-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("invoice", "0003_auto_20201108_2021")]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="net_amount",
            field=models.FloatField(blank=True, null=True),
        )
    ]
